nyturl  = "https://www.nytimes.com/interactive/polls/donald-trump-approval-rating-polls.html"

csvurl  = "https://www.nytimes.com/newsgraphics/polls/approval/president.csv"

selected_pollsters = ['CNN/SSRS',
                      'Gallup',
                      'Ipsos',
                      'Pew Research Center',
                      'Quinnipiac University',
                      'The New York Times/Siena University']

selected_only = true
